# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb",
         "say_goodbye": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://worc3131.github.io/nbdev_template/"

git_url = "https://github.com/worc3131/nbdev_template/tree/master/"

def custom_doc_links(name): return None
